// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:playbazaar/models/hive_models/hive_message_model.dart';
import 'package:playbazaar/models/hive_models/recent_interacted_user_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HiveMessageModelAdapter());
    registerAdapter(RecentUserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HiveMessageModelAdapter());
    registerAdapter(RecentUserAdapter());
  }
}
